source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
platform :ios, '10.0'
use_frameworks!

def app_pods
    pod 'MaterialComponents/AppBar'
end

target 'MDCAppBarDemo' do
    app_pods
end
